In [1]:
from selenium import webdriver
from selenium.webdriver.edge.options import Options
import pandas as pd
from selenium.webdriver.common.by import By
import time

In [2]:
options=Options()
options.add_experimental_option('detach',True)
driver=webdriver.Edge(options=options)
driver.get('https://www.investing.com/commodities/rough-rice-historical-data')

In [3]:
css_selector='#__next > div.desktop\:relative.desktop\:bg-background-default > div.relative.flex > div.pt-5.md\:pt-10.xl\:container.xl\:mx-auto.font-sans-v2.antialiased.text-\[\#232526\].grid.grid-cols-1.md\:grid-cols-\[1fr_72px\].lg\:grid-cols-\[1fr_420px\].px-4.sm\:px-6.md\:px-7.md\:gap-6.lg\:px-8.lg\:gap-8.flex-1 > div.min-w-0 > div.mb-4.md\:mb-10 > div.sm\:flex.sm\:items-end.sm\:justify-between > div.relative.flex.items-center.md\:gap-6 > div'
setday = driver.find_elements(By.CSS_SELECTOR, css_selector)
setday[1].click()

In [4]:
time.sleep(3)
start_day=driver.find_elements(By.CSS_SELECTOR,'#__next > div.desktop\:relative.desktop\:bg-background-default > div.relative.flex > div.pt-5.md\:pt-10.xl\:container.xl\:mx-auto.font-sans-v2.antialiased.text-\[\#232526\].grid.grid-cols-1.md\:grid-cols-\[1fr_72px\].lg\:grid-cols-\[1fr_420px\].px-4.sm\:px-6.md\:px-7.md\:gap-6.lg\:px-8.lg\:gap-8.flex-1 > div.min-w-0 > div.mb-4.md\:mb-10 > div.sm\:flex.sm\:items-end.sm\:justify-between > div.relative.flex.items-center.md\:gap-6 > div.absolute.inline-flex.p-4.flex-col.items-end.gap-4.rounded.border.border-solid.bg-\[\#fff\].shadow-secondary.top-\[42px\].right-0.z-5 > div.flex.items-start.gap-3 > div:nth-child(1)')
start=start_day[0].click()

In [5]:
apply=driver.find_elements(By.CSS_SELECTOR,'#__next > div.desktop\:relative.desktop\:bg-background-default > div.relative.flex > div.pt-5.md\:pt-10.xl\:container.xl\:mx-auto.font-sans-v2.antialiased.text-\[\#232526\].grid.grid-cols-1.md\:grid-cols-\[1fr_72px\].lg\:grid-cols-\[1fr_420px\].px-4.sm\:px-6.md\:px-7.md\:gap-6.lg\:px-8.lg\:gap-8.flex-1 > div.min-w-0 > div.mb-4.md\:mb-10 > div.sm\:flex.sm\:items-end.sm\:justify-between > div.relative.flex.items-center.md\:gap-6 > div.absolute.inline-flex.p-4.flex-col.items-end.gap-4.rounded.border.border-solid.bg-\[\#fff\].shadow-secondary.top-\[42px\].right-0.z-5 > div.flex.py-2\.5.pl-4.pr-6.items-center.gap-3.rounded.bg-v2-blue.shadow-button.hover\:bg-\[\#116BCC\].cursor-pointer')
apply[0].click()

In [6]:
date=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td/time')
prices=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[2]')
open=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[3]')
high=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[4]')
low=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[5]')
vol=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[6]')
change=driver.find_elements('xpath','//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[3]/div[3]/table/tbody/tr/td[7]')

In [7]:
data_len=len(date)
save={
    'time':[],
    'price':[],
    'open':[],
    'high':[],
    'low':[],
    'vol':[],
    'change':[]
}
for day in range(data_len):
    
    save['time'].append(date[day].text)
    save['price'].append(prices[day].text)
    save['open'].append(open[day].text)
    save['high'].append(high[day].text)
    save['low'].append(low[day].text)
    save['vol'].append(vol[day].text)
    save['change'].append(change[day].text)
df=pd.DataFrame(save)

In [10]:
df.to_csv('rough_rice.csv', index=False)

In [11]:
df

            time   price    open    high     low    vol  change
0     11/03/2023  16.215  16.130  16.180  16.115  0.02K  +0.34%
1     11/02/2023  16.160  16.360  16.360  16.125  0.06K  -0.52%
2     11/01/2023  16.245  16.335  16.340  16.205  0.04K  +0.78%
3     10/31/2023  16.120  16.100  16.135  16.070  0.11K  +0.31%
4     10/30/2023  16.070  16.195  16.210  15.995  0.55K  -0.89%
...          ...     ...     ...     ...     ...    ...     ...
3489  01/08/2010  14.705  14.730  14.730  14.730  0.05K  -0.07%
3490  01/07/2010  14.715  14.715  14.715  14.715  0.04K  -0.44%
3491  01/06/2010  14.780  14.780  14.780  14.780  0.06K  +0.07%
3492  01/05/2010  14.770  14.775  14.775  14.770  0.07K  -0.27%
3493  01/04/2010  14.810  14.755  14.930  14.755  0.16K  +1.68%

[3494 rows x 7 columns]